### ISSUE TITLE
Requirements: DRAFT

### ISSUE THREAD

**Issue by eko24ive** [eko24ive/IT-Revolution-2017-web-requirements#1]
#### Things we encourage to use:
- ES6 and ES7
- AMP
- Webpack, Gulp, Grunt  or any other task runner
- CSS Grids or Flexbox

#### Things we NOT encourage to use:
- Bootstrap, Foundation or any other CSS framework
- jQuery, Zepto, Cash or any other DOM manipulation library

I propose following topic for trial application - "GitHub Issue advanced browser" which certainly have to use GitHub API

**Comment by eko24ive** [comment]
@DarthDonald perhaps we need create third list with e.g. "things that should used/implemented" to correctly distribute 'good-to-have' and 'must-be-implemented' tasks ?

**Comment by DarthDonald** [comment]
Things we encourage to use:
+ CSS preprocessors
+ REST API

Things we NOT encourage to use:
+ Firebase

**Comment by eko24ive** [comment]
REST API and Firebase is not relevant since contestants would use GitHub API if we agree on my proposal for the topic of trial aplication.
Agreed on prepocessors.
@DarthDonald still waiting your answer for additional list !

**Comment by eko24ive** [comment]
Regarding prohibition of CSS-frameworks, I'd like to add that feature specific libs are ok to use, e.g. - [animate.css](https://daneden.github.io/animate.css/) and so on.

**Comment by eko24ive** [comment]
@DarthDonald is it necessary to specify testing and code coverage as trial task requirement or it'll be overkill ?

**Comment by DarthDonald** [comment]
@eko24ive testing is overkill and not necessary but If the main task is accomplished we will add as extra points

**Comment by eko24ive** [comment]
@DarthDonald ok, fine.

**Comment by DarthDonald** [comment]
@eko24ive Please, create another issue with your purpose `"GitHub Issue advanced browser" which certainly have to use GitHub API`

**Comment by eko24ive** [comment]
Okay, in progress...

**Comment by eko24ive** [comment]
@DarthDonald, I've created issue with my proposal #2 
Take a look please

**Comment by eko24ive** [comment]
@DarthDonald as long as task proposal is approved #2 and features are prioritized #3 we could sum up the desired stack of technologies for participants. Do you have any additions or objections to discussed technologies/libraries etc. ?

**Comment by DarthDonald** [comment]
@eko24ive No, I haven't

**Comment by eko24ive** [comment]
Ok, so according to our discussions here is the desired stack of technologies: 

#### Things we encourage to use:
- ES6/ES7
- PWA
- Webpack, Gulp, Grunt  or any other task runner
- Using package manager Yarn, NPM, etc.
- CSS Grids or/and Flexbox
- CSS preprocessors
- REST API

#### Things we NOT encourage to use:
- Bootstrap, Foundation or any other CSS framework
- jQuery, Zepto, Cash or any other direct DOM manipulation libraries
- Firebase or any other cloud PaaS database solutions

#### Extra things we'd like to see 
- Heroku deployment
- Unit, Integrational and E2E testing

---

@DarthDonald @andrewchopko approve or reject

**Comment by DarthDonald** [comment]
@eko24ive approve

**Comment by andrewchopko** [comment]
@eko24ive AMP or PWA or both

**Comment by eko24ive** [comment]
PWA for sure. AMP is not restricted though, but PWA is preferred.

**Comment by andrewchopko** [comment]
approve ^_^

**Comment by eko24ive** [comment]
@DarthDonald I was wondering should we prohibit submissions which are based on platform wrappers - e.g. Electron, React Native, Ionic and etc. ?

**Comment by eko24ive** [comment]
quick followup - I think we might treat those submissions with some extra points only if must have requirements are met. It would be nice to see submissions based on isomorphic solutions. Let me know what you think.

**Comment by eko24ive** [comment]
Guys @DarthDonald @andrewchopko,
I'd like to extend this one:
>Heroku deployment

Some contestants might use tech stack which is not supported by Heroku (e.g. .Net and etc.) so I'd like to add Microsoft Azure and AWS as additional cloud platforms for application hosting.

**Comment by eko24ive** [comment]
Approved internally
