### ISSUE TITLE
Topic Proposal: GitHub Issue Browser

### ISSUE THREAD

**Issue by eko24ive** [eko24ive/IT-Revolution-2017-web-requirements#2]
# GitHub Issue Browser (GIB)

##### Disclaimer
Demo repo for this proposal would be https://github.com/facebook/react

### Abstract
GIB would be a web-app which allows users to browse issues of a specific repository with following key-features:
 - Intelligent labels processing (ILP)
 - Issue allocation (IA) by its role based on intelligent labels processing (ILP) logic:
    - Bug
    - Question
    - Feature
    - Enhancement
 - Additional issue filtering based on data obtained from issue allocation logic
 - Processing issues with multiple labels 
 - Detect relevant pull requests (PRs) for specific issue if there any
 - Calculate Feature Integration (FI) ratio of repository
 - Calculate Defect Fix (DF) ratio of repository
 - Calculate top contributors and it's Contribution Zone (CZ) of repository
 - Calculate rating for issue reporter or PR "opener"
 - Calculate rating for issue resolver or PR "merger"
 - Convert issues to chat with WebSocket
 - Repository users mentions/reviews

## Features breakdown
At the moment of writing, this proposal react repo contains ~600 open issues. Some issue is labeled with one or more labels or not marked at all. For example, number 600 itself might be confusing for the developer, so he'd think that react is quite unstable technology and maybe it's better to choose something else.  

But if we dive deeper we'd see that there is a label called `Type: Bug` which is used to mark bug related issues, and amount of issues with such label is ~200 and ~140 of them is closed (~40 issues are open). 

So 40 open bug-related issues is much less than a total amount of issues. So perhaps react itself isn't so bad and unstable as we could think for the first time. 

Moreover, if we'd take a close look at open bug related issues we got another detailed information them, which is:
 - Some issues have additional labels: 
    - `Component: DOM`
    - `Browser: IE`
 - Some issues contain references to another issue and even PRs
 - References issues/PRs might have their own state (closed/open) and referenced issues/PRs

These details have a direct impact on features for our web app, so let's describe them more precisely.

### Intelligent labels processing (ILP) and Issue allocation (IA)
For every newly created repository, there are 7 default labels:  bug, duplicate, enhancement, help wanted, invalid, question, wont-fix. The developer is free to change and delete them or create new. It is a common situation that actively developed technologies have a lot more labels to make collaboration more efficient and comfortable. 

We can see all labels of react repository on this page https://github.com/facebook/react/labels. At the moment there are 50 labels. It's easy to see that there is a lot of "two-level" labels composed using simple scheme `{type}:{subtype}`, e.g.:

![image](https://user-images.githubusercontent.com/25591824/30119342-0e70ad6a-932e-11e7-8dd0-c0403bdba8e0.png)

So there is type "Resolution" and four its subtypes: Duplicate, Invalid, Unsolved and Wontifx.
Certainly, there are much more types of labels for react repo. Our goal is to process this labels in the most efficient way.
A prototype of browsing issues composed by intelligent labels processing and pre-filtered with help of issue allocation by its role based on labels processing logic:

![image](https://user-images.githubusercontent.com/25591824/30120741-680f5cf0-9332-11e7-9879-35c8935f3c8b.png)

### Processing issues with multiple labels
Of course, there might be situations where some issues need to be additionally specified with another label. For example, some bug occurs for component "DOM" and reproduces only for IE:

![image](https://user-images.githubusercontent.com/25591824/30120390-5b3a36b8-9331-11e7-9f02-44b1e695f169.png)

Therefore we need also indicate such labels if we're browsing through issues we've detected as 'Bug':
![image](https://user-images.githubusercontent.com/25591824/30120775-7bd0a4ba-9332-11e7-8c55-982347c579ac.png)

And of course, we have to omit "Bug" label since we're already browsing bug-related section. 

### Detect relevant pull requests (PRs) for specific issue if there any
Despite the type of issue, more often than not it requires some changes to repository contents - code, assets or else. This changes often performed via pull requests by contributors or integrated "silently" directly to master/development branch by repo owners.
Github API provides an ability to retrieve relevant PRs or another issue for the given one. Also, users might point out to sideway issues and PRs in comments as well, so we need to keep an eye on them too. Finally, all relevant PRs and issues we can show in this way:  
![image](https://user-images.githubusercontent.com/25591824/30165644-7274c240-93e9-11e7-9656-0fb99773eb6b.png)

### Calculate Feature Integration (FI) ratio of repository
FI ration is basically an indication of the average amount of time passed from creating an issue with a feature request and to merging relevant PR or closing issue itself for this feature. The only one pointy thing is that we need to omit issues which were closed due to invalid requirements for the feature or etc. 

---
In general formula would look like this:  
t = (T1 + T2 + T3 + ... + Tn) / n

Where:  
T - amount of time passed between opening issue and it closing or merging relevant PRs,  
n - amount of all issues we're going through  
t - FI ratio  

---

For example, lets take a look at this three demo issues:

| No. | Issue title                               | Created at             | Merged at             | Issue status |
|-----|-------------------------------------------|------------------------|-----------------------|--------------|
| 1   | Warnings should use console.warn          | 16:13:00 Mar 12, 2017  | 19:14:00 Mar 14, 2017 | Closed       |
| 2   | Tests: toTree on a rendered array         | 08:46:00 Jun 09, 2017  |                       | Open         |
| 3   | Warn for unknown non-lowercase attributes | 13:00:00 Jan 12, 2017  | 18:15:00 Aug 12, 2017 | Closed       |

So, one is "open" so we don't use it for our calculation, we'd use two issues with "closed" status. For simplicity let's use "days" as value for our FI ratio. For issue #1 - 2 days passed before the merge. For issue #3 - 212 days passed before the merge.

Using formula: (2 + 212) / 2 = 107. 

Although "107" is a really big amount of time for the average issue to fix, we surely understand that our formula lacks the additional logic to correctly detect this index. For example, we don't know from the beginning how "complex" was the feature to implement or bug to fix, meaning that issue #3 could be really hard to do and 212 days spent on it is really fine. We'll discuss this case later.

**From now on keep in mind that we've worked with imperfect FI ratio formula**

But for now, we have another helpful information regarding FI ration - *rhythm* of the repo. By this, I mean that we know how long it took for the "fastest" and "longest" issue to fix/implement. This would help us to indicate actual state of FI ratio - is it awesome, good, average, bad or terrible.

Here is a simple example how we can detect a state of FI ratio:  
![image](https://user-images.githubusercontent.com/25591824/30170582-2d542534-93f8-11e7-9dfb-8ca52660f3c6.png)

So, as you might see the closer FI ration to "fastest" issue - the better. Here is the distribution of FI ration state values:
- Awesome: 12.5%
- Good: 12.5%
- Average: 25%
- Bad: 25%
- Terrible: 25%

Such distribution was made for demonstration purposes. Contestants are free to do it in the way they want to.

The last thing we could do - display percent value for FI ratio. Knowing that 2 equals to 0% and 212 is 100% our 107 value would be ~50%. But if our percent value would be less than 50 - we have to "swap" it because we want to show success-value and we're calculating failure-value. So for 35%, we had to show 65%.

At this point displaying FI ration to a user is not a big deal, since we know FI ration and its state.
For our specific case I'd love to see it this way:  
![image](https://user-images.githubusercontent.com/25591824/30172101-8061b6de-93fc-11e7-9fda-7f9658304963.png)

And for example "awesome" FI ratio would look like this:  
![image](https://user-images.githubusercontent.com/25591824/30172284-17f05e9c-93fd-11e7-962c-509a57ac7e3c.png)

Regarding imperfection of formula - it's up to contestants to develop more efficient and precise way to calculate FI ratio. On the other hand, for myself, I could do following. Let's represent random 40 issue on a chart with its "life time" value:
![image](https://user-images.githubusercontent.com/25591824/30174337-6994ff90-9403-11e7-909f-a26343d8bb1d.png)

Pretty messy. Let's sort them out from fastest to longest:  
![image](https://user-images.githubusercontent.com/25591824/30174258-1c7a1880-9403-11e7-8f0c-dca788c6f8c2.png)

Nice, now we can divide some issues into groups to describe FI ratio in a more verbose way, for example:  
![image](https://user-images.githubusercontent.com/25591824/30174530-1434214c-9404-11e7-9504-78ed16b365d1.png)

And basing on information from "Group 1" we could put some encouraging messages, like:  
![image](https://user-images.githubusercontent.com/25591824/30174763-d07ed572-9404-11e7-9559-da22dd70ac21.png)
  
and for the "Group 5" it may look like this:  
![image](https://user-images.githubusercontent.com/25591824/30174725-b586360c-9404-11e7-823f-a441d6ab83a2.png)  

Or we can even go with fully described information about our five groups, but I think it's more boring:  
![image](https://user-images.githubusercontent.com/25591824/30175314-bcf9909e-9406-11e7-8409-e4c1e68dcf8e.png)

### Calculate Defect Fix (DF) ratio of repository
Calculations of Defect Fix ration of the repo is pretty much similar to FI ratio calculation, after implementation of FI calculation logic it shouldn't be hard to calculate DF ratio. Though, we have same challenge to detect bug-related issues and PRs based on issue allocation (IA) and intelligent labels processing (ILB)

DF Ratio card could look like this:  
![image](https://user-images.githubusercontent.com/25591824/30175632-eb88c35c-9407-11e7-980d-6f52cff64b8b.png)

Overall, GitHub [Statistic](https://developer.github.com/v3/repos/statistics/) API endpoints are a great place to find data for such purposes like DF and FI ratios and other useful information. Repository [Pulse](https://github.com/facebook/react/pulse) and [Graphs](https://github.com/facebook/react/graphs) page is a nice way to see how GitHub represents data from its API.

### Calculate top contributors and it's Contribution Zone (CZ) of repository
Despite GitHub already calculates top contributors, we could enhance this feature in a lot of ways. For example, I'm as a developer would like to know who is the top contributor for label `Component: Addons / TransitionGroup` so I could assign this person if I'll open an issue or create PR. Also, such feature would help to understand "area of expertise" of a specific contributor. Certainly, implementing this feature is directly wired with ILP logic, which would greatly simplify the process.

UI for some kind of board of top contributors with their CZ might look like this:  
![image](https://user-images.githubusercontent.com/25591824/30201895-057c1c14-9485-11e7-9685-19de3deb5dbe.png)

We also could indicate the rank of users who reply on issues/PRs with labels similar to their CZ:  
![image](https://user-images.githubusercontent.com/25591824/30202335-c6f3de1c-9486-11e7-9c1a-f1a1e8aac5c9.png)

### Calculate rating for issue reporter or PR "opener"
Yet another feature to improve users experience of using GitHub. As a repository owner or average developer I'd would love to see how much issues of a particular user was valid and meaningful and PRs merged. We can call this "Contributor Rating". Contributor Rating would reflect such information in the UI-appropriate way. Challenge for the developer is to progress through all PRs and issues of a specific person in particular repository and calculate how many closed issues were resolved in the appropriate way (they wasn't closed as invalid or un relevant) and how many closed PRs was merged.  
With this data our formula could look like this:

---

R = Io / Ir + Po / Pr  

Where:
 - Io - amount of issues opened by particular user
 - Ir - amount of successfully resolved closed issues opened by particular user
 - Po - amount of pull requests opened by particular user
 - Pr - amount of successfully resolved closed pull requests opened by particular user
 - R - Contributor Rating

---

For example, if we know each piece of this data our figures would look like this:

| User      | Issues opened | Issues resolved | PRs opened | PRs resolved | Contributor Rating |
|-----------|:-------------:|:---------------:|:----------:|:------------:|:------------------:|
| johndoe1  |       21      |        13       |      4     |       2      |   **3.61538462**   |
| davesmith |       2       |        0        |      0     |       0      |        **0**       |
| janedoe   |       15      |        5        |      2     |       2      |        **4**       |

As seen - we can easily run into a case when user has only opened issues/PRs but closed ones. For such situations, it's better to omit the value of contributors rating for UI purposes because it could be a bad experience to display it.

UI implementation of this data may be shown like:  
![image](https://user-images.githubusercontent.com/25591824/30421540-c1726ff8-9945-11e7-9b1b-3a92c7efd84f.png)

## Calculate rating for issue resolver or PR "merger"
Resolver Rating is quite the same thing as Contributor Rating, but for RR we only count the sum of all closed issues and PRs and "align" resulted value to other, for example here is our data:

| User      | Issues closed | PRs closed | Resolver Rating |
|-----------|:-------------:|:----------:|:---------------:|
| johndoe1  |      113      |     54     |      **167**    |
| davesmith |      132      |     43     |      **175**    |
| janedoe   |       78      |     20     |      **98**     |
  
  
Not only we have the rating value, we may display it on a 100-ish scale, making our greatest rating value `175` is equal to 100%:

| User      | Issues closed | PRs closed | Resolver Rating | Aligned Rating |
|-----------|:-------------:|:----------:|:---------------:|:--------------:|
| johndoe1  |      113      |     54     |       167       |    **95.4%**   |
| davesmith |      132      |     43     |       175       |    **100%**    |
| janedoe   |       78      |     20     |        98       |    **55.4%**   |

In a case with Resolver Rating, it's no need to omit it when data from one of two columns equal zero.
We may display the aligned value in the way we did it for Contributor Rating.

---
**It's important to remember that user may have both Contributor Rating and Resolver Rating at the same time**

---

### Repository users mentions/reviews
This could be not only front end but backend involving task.
The idea is to provide the ability for users to leave their small review for specific repo which would be shown for all users. Perhaps it'd be good to use the mechanic of Steam reviews and use same patterns for reviews processing.

#### Wrap as Chrome/Firefox etc. extensions
This could be challenging thing to implement but also would give additional experience to contestants. Further, contestants could publish their project as open source to GitHub which be nice investment both for portfolio and GitHub community as well

**Comment by eko24ive** [comment]
FYI: If this topic would be chosen we might need to create "demo" repo to evaluate readiness and quality of contestants submissions

**Comment by eko24ive** [comment]
Regarding top collaborators calculation - it probably would be nice to keep track of 'reactions' (👍,👎,😄,🎉,😕,❤️) of users to collaborators comments

**Comment by DarthDonald** [comment]
Nice, but I think is very long task, we can write it shorter

**Comment by DarthDonald** [comment]
Transofrm each issue into chat. Data from this chat have to be stored on your own database (not firebase). Use Websockets for real-time update fetching . Design chat UI. Chat must support text messages, implementing support for image, audio and video messaging are highly appreciated. Implement infinite scroll for showing previous and following messages. User can be shown n last messages, where n > 10. You can realize editing and deleting messages features for current user. Line endings and tabs of message must be parsed.

**Comment by eko24ive** [comment]
Ok, I'm approving your ideas regarding issues.
I'll update proposal with these, then we need to discuss priority of each feature and if everything clear - close this issue with final proposal approve.

**Comment by eko24ive** [comment]
@DarthDonald I've added your proposal of chat-mode for issues into the specification. Also, I realized that features of writing/editing/deleting messages requires authorization of particular user using GitHub Auth endpoints. **This might take extra time for contestants to implement it**.  So we have to be aware of this when estimating whole proposal itself and prioritizing features. If you think it's better to simplify or even drop this feature.

**Comment by DarthDonald** [comment]
@eko24ive What if they create the auth for the chat on their own backend side?

**Comment by eko24ive** [comment]
Seems legit. Then we're good to go to begin features prioritizing. @andrewchopko if you approve this proposal - let us know and close the issue.

**Comment by andrewchopko** [comment]
@eko24ive @DarthDonald nice work guyzz, fully agree with you, approve o/
