### ISSUE TITLE
Features prioritization 

### ISSUE THREAD

**Issue by eko24ive** [eko24ive/IT-Revolution-2017-web-requirements#3]
As said in #2 here is our list of features:
 - Intelligent labels processing (ILP)
 - Issue allocation (IA) by its role based on intelligent labels processing (ILP) logic
 - Additional issue filtering based on data obtained from issue allocation logic
 - Processing issues with multiple labels 
 - Detect relevant pull requests (PRs) for specific issue if there any
 - Calculate Feature Integration (FI) ratio of repository
 - Calculate Defect Fix (DF) ratio of repository
 - Calculate top contributors and it's Contribution Zone (CZ) of repository
 - Calculate rating for issue reporter or PR "opener"
 - Calculate rating for issue resolver or PR "merger"
 - Convert issues to chat with WebSocket
 - Repository users mentions/reviews

---

Here is how I'd like to prioritize them:

#### Must-have features
 1) Intelligent labels processing (ILP)
 2) Issue allocation (IA) by its role based on intelligent labels processing (ILP) logic
 3) Additional issue filtering based on data obtained from issue allocation logic
 4) Convert issues to chat with WebSocket
 5) Repository users mentions/reviews
 6) Processing issues with multiple labels 
 7) Detect relevant pull requests (PRs) for specific issue if there any

#### Extra features
 - Calculate Feature Integration (FI) ratio of repository
 - Calculate Defect Fix (DF) ratio of repository
 - Calculate top contributors and it's Contribution Zone (CZ) of repository
 - Calculate rating for issue reporter or PR "opener"
 - Calculate rating for issue resolver or PR "merger"

**Comment by eko24ive** [comment]
@DarthDonald what do you think ?

**Comment by DarthDonald** [comment]
@eko24ive 
1. Must be `Chat with WebSocket for every issue`
2. Too much `Must-have features`

**Comment by eko24ive** [comment]
@DarthDonald fine, we can move chat-issues to first place. Which issues you'd like to downgrade?

**Comment by DarthDonald** [comment]
@eko24ive `Detect relevant pull requests (PRs) for specific issue if there any` and `Additional issue filtering based on data obtained from issue allocation logic`

**Comment by eko24ive** [comment]
@DarthDonald lets leave `Additional issue filtering based on data obtained from issue allocation logic` and move `Repository users mentions/reviews` instead. What do you say ?

**Comment by DarthDonald** [comment]
@eko24ive I think `Repository users mentions/reviews` more important than `Detect relevant pull requests (PRs) for specific issue if there any`

**Comment by eko24ive** [comment]
@DarthDonald Agreed, lets stick with this list.

**Comment by eko24ive** [comment]
So final version:


#### Must-have features
 1) Intelligent labels processing (ILP)
 2) Issue allocation (IA) by its role based on intelligent labels processing (ILP) logic
 3) Convert issues to chat with WebSocket
 4) Repository users mentions/reviews
 5) Processing issues with multiple labels 

#### Extra features
 - Additional issue filtering based on data obtained from issue allocation logic
 - Calculate Feature Integration (FI) ratio of repository
 - Calculate Defect Fix (DF) ratio of repository
 - Calculate top contributors and it's Contribution Zone (CZ) of repository
 - Calculate rating for issue reporter or PR "opener"
 - Calculate rating for issue resolver or PR "merger"
 - Detect relevant pull requests (PRs) for specific issue if there any

**Comment by eko24ive** [comment]
@andrewchopko if you're ok with this list - approve and close.

**Comment by andrewchopko** [comment]
👌
