### ISSUE TITLE
Project evaluation, progress milestones development

### ISSUE THREAD

**Issue by eko24ive** [eko24ive/IT-Revolution-2017-web-requirements#5]
We need to develop appropriate acceptance criteria for submissions to easily detect sufficient and elegant solutions. Therefore we might need to create specific milestones which we'd use as a pattern to compare with submission. Besides, well-described table of points (feature - point) could also do the trick and help us evaluate particular submission.

As long as this is public repo - perhaps it's better to discuss this subject in private gist for the sake of spirit of competition. Let me know if we need to create private gist, so I'll share access links with you. when discussion and competition are complete - we'll share link here.

**Comment by DarthDonald** [comment]
@eko24ive Yes, please create private gist.

**Comment by eko24ive** [comment]
Ok.

**Comment by eko24ive** [comment]
Feature evaluation approved, link would be shared about when project submission is over
